### ISSUE TITLE
CDN shows only 1.5.7

### ISSUE THREAD

**Issue by iranzo** [GalleriaJS/galleria#414]
Hi
I would expect to have a 'latest' or 'stable' link on the CDN pointing to 1.6.1 as listed on the github page.

Is this in progress? 

Thanks,
Pablo

**Comment by GalleriaJS** [comment]
https://github.com/cdnjs/cdnjs/issues/13524

if this is urgent, open an issue there and create a pull request for the latest galleria version.

**Comment by GalleriaJS** [comment]
I updated the readme to reference jsdeliver instead.

**Comment by iranzo** [comment]
Thanks!
